# Generated by Django 2.1.3 on 2018-11-25 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bluetooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('mac_address', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('available', models.BooleanField(default=False)),
                ('paired', models.BooleanField(default=False)),
                ('strength', models.CharField(max_length=4, null=True)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('primal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BluetoothDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mac_address', models.CharField(max_length=100, null=True)),
                ('powered', models.BooleanField(default=False)),
                ('discoverable', models.BooleanField(default=False)),
                ('pairable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocalServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='worker')),
                ('service_id', models.CharField(max_length=100, null=True)),
                ('worker_number', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('mac_address', models.CharField(max_length=100, null=True)),
                ('authenticated', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MibandEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shutdown', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ssid', models.CharField(max_length=100, null=True)),
                ('mac_address', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('encryption_type', models.CharField(max_length=100, null=True)),
                ('available', models.BooleanField(default=False)),
                ('connected', models.BooleanField(default=False)),
                ('strength', models.CharField(max_length=4, null=True)),
                ('known', models.BooleanField(default=False)),
                ('on_boot', models.BooleanField(default=False)),
                ('device_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WifiDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('wifi_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oikos.WifiDevice')),
                ('rand_ip', models.PositiveIntegerField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('on_boot', models.BooleanField(default=False)),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='wifi',
            name='wifi_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oikos.WifiDevice'),
        ),
        migrations.AddField(
            model_name='localservices',
            name='miband',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oikos.Miband'),
        ),
        migrations.AddField(
            model_name='bluetooth',
            name='bluetooth_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oikos.BluetoothDevice'),
        ),
        migrations.AddField(
            model_name='bluetooth',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
