# Generated by Django 2.1.5 on 2019-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oikos', '0002_auto_20190217_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluetooth',
            name='mac_address',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bluetoothdevice',
            name='mac_address',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='mac_address',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
